version: '3.6'

services:
  user_db:
    container_name: user_db
    image: postgres:10
    ports:
      - 2345:5432
    volumes: 
      - ./user_db_pg_data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: password

  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: DockerFileGateway
    ports:
      - 3000:8080
    volumes: 
      - ./gateway:/opt/app
    depends_on: 
      - user_db
    environment: 
      DATABASE_URL: postgres://postgres:password@user_db:5432/postgres
    command: sh -c 'npm install && LOG_LEVEL=debug node server.js'

  cat:
    container_name: cat
    build:
      context: .
      dockerfile: DockerFileCat
    ports:
      - 8000:8000
    volumes:
      - ./cat:/opt/app
    command: sh -c 'pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    
  dog:
    container_name: dog
    build:
      context: .
      dockerfile: DockerFileDog
    ports:
      - 8001:8000
    volumes:
      - ./dog:/opt/app
    command: sh -c 'pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000'