version: '3.6'

services:

  cat:
    container_name: cat
    build:
      context: .
      dockerfile: DockerFileCat
    ports:
      - 8000:8000
    volumes:
      - ./cat:/opt/app
    command: sh -c 'pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    
  dog:
    container_name: dog
    build:
      context: .
      dockerfile: DockerFileDog
    ports:
      - 8001:8000
    volumes:
      - ./dog:/opt/app
    command: sh -c 'pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000'

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: DockerFileAuth
    ports:
      - 8002:8000
    volumes:
      - ./auth:/opt/app
    command: sh -c 'pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000'