http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  static_rest:
    host: localhost
    paths: '/static/rest_framework/*'
  cat:
    host: localhost
    paths: '/cat/*'
  api-auth:
    host: localhost
    paths: '/api-auth/*'
  dog:
    host: localhost
    paths: '/dog/*'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  cat:
    url: 'http://cat:8000'
  dog:
    url: 'http://dog:8000'
policies:
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - jwt-auth
  - basic-auth
  - session-auth
  - local-auth
  - auth-secure
pipelines:
  static_rest:
    apiEndpoints:
      - static_rest
    policies:
      - proxy:
          - action:
              serviceEndpoint: dog
              changeOrigin: false
  dog:
    apiEndpoints:
      - dog
    policies:
      # - cors:
      #     - action:
      #         origin: '*'
      - auth-secure:
      - basic-auth:
          - action:
              passThrough: true
      - jwt-auth:
          - action:
              passThrough: true
      - proxy:
          - action:
              serviceEndpoint: dog
              # changeOrigin: true
  cat:
    apiEndpoints:
      - cat
      - api-auth
    policies:
      # - cors:
      #     - action:
      #         origin: '*'
      - proxy:
          - action:
              serviceEndpoint: cat
              changeOrigin: false